### ISSUE TITLE
Introduction animation splash view to tall for iPhone 6

### ISSUE THREAD

**Issue by KilianB** [Aashu-Dubey/React-Native-UI-Templates#3]
![image](https://user-images.githubusercontent.com/9025925/195982020-7457a90c-3da3-4997-824e-201987f322ed.png)
![image](https://user-images.githubusercontent.com/9025925/195982026-6454cb36-53f5-4b11-ae96-2b7a056d0d53.png)

I just integrated the introduction animation into a project and the welcome image is out of bounds for this device shifting everything to the bottom.

**Comment by Aashu-Dubey** [comment]
Thanks for reporting the issue, can you please check with the latest changes to see if the issue is fixed now?

**Comment by KilianB** [comment]
Thanks it is looking a lot better now.  As I had to copy those changes into my project manually it would have been nice if the fix could have been an individual commit. This way it is a bit more obvious on which changes I should adapt.
